"""empty message

Revision ID: 04a3d5f956e0
Revises: 33a47c5ac331
Create Date: 2020-12-17 20:56:34.040748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a3d5f956e0'
down_revision = '33a47c5ac331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'reserves', ['clothes_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reserves', type_='unique')
    # ### end Alembic commands ###
