"""empty message

Revision ID: 0596e18e4b13
Revises: 6cec09ea7393
Create Date: 2020-12-15 18:01:27.007544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0596e18e4b13'
down_revision = '6cec09ea7393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clothes_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clothes_id'], ['clothes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clothes', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('auth0_id', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth0_id')
    op.drop_column('clothes', 'status')
    op.drop_table('reserves')
    # ### end Alembic commands ###
