"""empty message

Revision ID: 4f0a2a0e7b8f
Revises: 4b2dccfd6b62
Create Date: 2020-12-17 23:14:36.031198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f0a2a0e7b8f'
down_revision = '4b2dccfd6b62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
